### ISSUE TITLE
你好 狼牙大神 你的修改C08PacketPlayerBlockPlacement中的代码有误

### ISSUE THREAD

**Issue by IzumiiKonata** [LangYa466/PacketFixMCP#1]
你重写readPacketData(PacketBuffer buf)干什么 没看懂 不应该是重写writePacketData(PacketBuffer buf)吗

**Comment by LangYa466** [comment]
写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭写错了😭

**Comment by IzumiiKonata** [comment]
👍
